Models/ErrorViewModel.cs
namespace RosePark.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Persona.cs
namespace RosePark.Models
{
    public class Persona
    {
        public int Id { get; set; }
        public string ? Nombres { get; set; }
        public string ? Apellidos { get; set; }
        public string ? Telefono { get; set; }
        public string ? Correo { get; set; }
        public string ? Contrasena { get; set; }
    }
}

Models/Usuario.cs
namespace RosePark.Models
{
    public class Usuario
    {
        public int Id { get; set; }
        public string? Cedula { get; set; }
        public string? Nombres { get; set; }
        public string? Apellidos { get; set; }
        public string? Correo { get; set; }
        public string? Contrasena { get; set; }
        public string? Telefono { get; set; }
        public string? Nacionalidad { get; set; }
        public DateTime? FechaNacimiento { get; set; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using RosePark.Models;

namespace RosePark.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/PersonalController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RosePark.Data;
using RosePark.Models;

namespace RosePark.Controllers
{
    public class PersonalController : Controller
    {
        public readonly BaseContext _context;
        
        public PersonalController(BaseContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Personal.ToListAsync());
        }

        public async Task <IActionResult> Detalles(int Id)
        {
            return View(await _context.Personal.FirstOrDefaultAsync(m=> m.Id == Id));
        }

        public async Task<IActionResult> Eliminar(int Id)
        {
            var Persona = await _context.Personal.FindAsync(Id);
            _context.Personal.Remove(Persona);
            
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public IActionResult Crear()
        {
            return View();
        }

        public IActionResult CrearPersonal(Persona p)
        {
            _context.Personal.Add(p);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RosePark.Data;
using RosePark.Models;

namespace RosePark.Controllers
{
    public class UsuariosController : Controller
    {
        public readonly BaseContext _context;

        public UsuariosController (BaseContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Usuarios.ToListAsync());
        }
        
        public async Task<IActionResult> Eliminar(int Id)
        {
            var Usuario = await _context.Usuarios.FindAsync(Id);
            _context.Usuarios.Remove(Usuario);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public IActionResult Crear()
        {
            return View();
        }

        public async Task <IActionResult> Detalles(int Id)
        {
            return View(await _context.Usuarios.FirstOrDefaultAsync(m=>m.Id == Id));
        }

        public IActionResult CrearUsuario(Usuario u)
        {
            _context.Usuarios.Add(u);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult EditarUsuario(int Id, Usuario U){
            _context.Usuarios.Update(U);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Home/Old/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Personal/Crear.cshtml
<h2>Creación de Usuario</h2>
<a asp-action="Index" class="btn btn-warning">Cancelar</a>

@model Persona
@{
    ViewData["Title"] = "Crear";
}

<form asp-action="CrearPersonal" method="post">
    <div class="form-group">
        <label asp-for="Nombres"></label>
        <input required asp-for="Nombres" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Apellidos"></label>
        <input required asp-for="Apellidos" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Telefono"></label>
        <input required asp-for="Telefono" class="form-control"/>
    </div>

    <div class="form-group">
        <label asp-for="Correo"></label>
        <input required asp-for="Correo" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Contrasena"></label>
        <input asp-for="Contrasena" required class="form-control" />
    </div>
    <div class="form-group text-center">
        <button type=submit class="btn btn-primary mt-4">Enviar</button>
    </div>
</form>

Views/Personal/Detalles.cshtml
<h2>Detalles Usuario @Model.Nombres</h2>
<a asp-action="Index" class="btn btn-warning">Volver</a>

<table class="table border">
    <tr class="border">
        <th>Nombres</th>
        <td>@Model.Nombres</td>
    </tr>
    <tr class="border">
        <th>Apellidos</th>
        <td>@Model.Apellidos</td>
    </tr>
    <tr class="border">
        <th>Correo</th>
        <td>@Model.Correo</td>
    </tr>
</table>

Views/Personal/Index.cshtml
<h2>Personales:</h2>
<a asp-action="Crear" class="btn btn-success">Crear Usuario</a>

<table class="table border">
    <tr class="border">
        <td>Nombres</td>
        <td>Apellidos</td>
        <td>Telefono</td>
        <td>Correo</td>
        <td>Acciones</td>
    </tr>
    
    <tr class="border">
        @foreach(var Personal in Model)
        {
        <tr>
            <td>@Personal.Nombres</td>
            <td>@Personal.Apellidos</td>
            <td>@Personal.Telefono</td>
            <td>@Personal.Correo</td>
            <td>
                <a asp-action="Detalles" asp-route-Id="@Personal.Id" class="btn btn-warning">Detalles</a>
                <a asp-action="Editar" class="btn btn-primary">Actualizar</a>
                <a asp-action="Eliminar" asp-route-Id="@Personal.Id" class="btn btn-danger">Eliminar</a>
            </td>
        </tr>
        }
    </tr>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RosePark</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RosePark.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RosePark</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personal" asp-action="Index">Personal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Copia" asp-action="Index">Copia</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RosePark - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Usuarios/Crear.cshtml
<h2>Creación de Usuario</h2>
<a asp-action="Index" class="btn btn-warning">Cancelar</a>

@model Usuario
@{
    ViewData["Title"] = "Crear";
}

<form asp-action="CrearUsuario" method="post">
    <div class="form-group">
        <label asp-for="Cedula"></label>
        <input required asp-for="Cedula" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Nombres"></label>
        <input required asp-for="Nombres" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Apellidos"></label>
        <input required asp-for="Apellidos" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Correo"></label>
        <input required asp-for="Correo" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Contrasena"></label>
        <input asp-for="Contrasena" required class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Telefono"></label>
        <input required asp-for="Telefono" class="form-control"/>
    </div>
    <div class="form-group">
        <label asp-for="Nacionalidad"></label>
        <input required asp-for="Nacionalidad" class="form-control"/>
    </div>
    <div class="form-group">
        <label asp-for="FechaNacimiento"></label>
        <input asp-for="FechaNacimiento" type="date" class="form-control"/>
    </div>
    <div class="form-group text-center">
        <button type=submit class="btn btn-primary mt-4">Enviar</button>
    </div>
</form>

Views/Usuarios/Detalles.cshtml
<h2>Detalles Usuario @Model.Nombres</h2>
<a asp-action="Index" class="btn btn-warning">Volver</a>

<table class="table border">
    <tr class="border">
        <th>Cedula</th>
        <td>@Model.Id</td>
    </tr>
    <tr class="border">
        <th>Nombres</th>
        <td>@Model.Nombres</td>
    </tr>
    <tr class="border">
        <th>Apellidos</th>
        <td>@Model.Apellidos</td>
    </tr>
    <tr class="border">
        <th>Correo</th>
        <td>@Model.Correo</td>
    </tr>
</table>

Views/Usuarios/Index.cshtml
<h2>Creación de Usuario</h2>
<a asp-action="Crear" class="btn btn-success">Crear Usuario</a>

<table class="table border">
    <tr class="border">
        <td>Id</td>
        <td>Cédula</td>
        <td>Nombre</td>
        <td>Apellido</td>
        <td>Correo</td>
        <td>Contraseña</td>
        <td>Telefono</td>
        <td>Nacionalidad</td>
        <td>Fecha de Nacimiento</td>
    </tr>
    
    <tr class="border">
        @foreach(var Usuario in Model)
        {
        <tr>
            <td>@Usuario.Id</td>
            <td>@Usuario.Cedula</td>
            <td>@Usuario.Nombres</td>
            <td>@Usuario.Apellidos</td>
            <td>@Usuario.Correo</td>
            <td>@Usuario.Contrasena</td>
            <td>@Usuario.Telefono</td>
            <td>@Usuario.Nacionalidad</td>
            <td>@Usuario.FechaNacimiento</td>
            <td>
                <a asp-action="Detalles" asp-route-Id="@Usuario.Id" class="btn btn-warning">Detalles</a>
                <a asp-action="Editar" class="btn btn-primary">Actualizar</a>
                <a asp-action="Eliminar" asp-route-Id="@Usuario.Id" class="btn btn-danger">Eliminar</a>
            </td>
        </tr>
        }
    </tr>
</table>